services:
  postgres:
    container_name: ${PROJECT_NAME}-postgres
    image: postgres:${POSTGRES_VERSION}
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
