services:
  contentfarm-api:
    image: ${CONTENTFARM_IMAGE_NAME}
    restart: always
    ports:
      - "80:80"
    depends_on:
      - elasticsearch
      - postgres
    environment:
      CONTENTFARM_AUTH_SERVER_URL: http://contentfarm-api:80/api
      POSTGRESQL_JDBC_URL: jdbc:postgresql://postgres:5432/postgres
      POSTGRESQL_USERNAME: test
      POSTGRESQL_PASSWORD: test
      ELASTICSEARCH_URL: elasticsearch:9200
      AWS_S3_ACCESS_KEY: ${AWS_S3_ACCESS_KEY} # from secret.env
      AWS_S3_SECRET_KEY: ${AWS_S3_SECRET_KEY} # from secret.env
      AWS_S3_REGION: ${AWS_S3_REGION} # from secret.env
      SPRING_PROFILES_ACTIVE: prod
      CONTENTFARM_PORT: ${CONTENTFARM_PORT}