spring:
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: test
    password: test
  config:
    import: classpath:.s3.secret.env[.properties]
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:80/api

file:
  operation:
    aws:
      s3:
        accessKey: ${AWS_S3_ACCESS_KEY}
        secretKey: ${AWS_S3_SECRET_KEY}
        region: ${AWS_S3_REGION}

logging:
  level:
    org.springframework.security: trace

kafka:
  producerBootstrapServer: localhost:9093
  consumerBootstrapServer: localhost:9093

elasticsearch:
  url: "localhost:9200"
